# Change these first
owner: darwinia-network # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - fewensa

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.darwinia.network
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://raw.githubusercontent.com/darwinia-network/devops/main/assets/darwinia/Darwinia-Background.svg
  name: Upptime
  introTitle: "Darwinia Upptime"
  introMessage: Darwinia Upptime, powered by [**upptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


sites:

  ### === darwinia rpc
  - name: rpc-darwinia-g1
    url: http://g1.darwinia2.darwinia.network:9944
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"id":1,"jsonrpc":"2.0","method": "eth_getBlockByNumber","params":["latest", false]}'
  - name: rpc-darwinia-c1
    url: http://c1.darwinia2.darwinia.network:9944
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"id":1,"jsonrpc":"2.0","method": "eth_getBlockByNumber","params":["latest", false]}'

  ### === crab rpc
  - name: rpc-crab-g1
    url: http://g1.crab2.darwinia.network:9944
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"id":1,"jsonrpc":"2.0","method": "eth_getBlockByNumber","params":["latest", false]}'

  - name: rpc-crab-c1
    url: http://c1.crab2.darwinia.network:9944
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"id":1,"jsonrpc":"2.0","method": "eth_getBlockByNumber","params":["latest", false]}'

